# Docker Compose Spec for Local Testing of Fairscape
services:
  setup:
    # image: ghcr.io/fairscape/setup:RELEASE.2025-05-27
    build: "./deploy/setup/"
    env_file: "./deploy/setup/setup.env"
    depends_on:
      - minio
      - fairscape-api
      - mongo
  fairscape-worker:
    build: "./"
    # image: ghcr.io/fairscape/mds_python:RELEASE.2025-05-21.v1
    env_file: "./deploy/docker_compose.env"
    command:
      - "python"
      - "fairscape_mds/worker.py"
    depends_on:
      - mongo
      - minio
  fairscape-api:
    build: "./"
    # image: ghcr.io/fairscape/mds_python:RELEASE.2025-05-21.v1
    env_file: "./deploy/docker_compose.env"
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - minio
  fairscape-frontend:
    image: ghcr.io/fairscape/fairscapefrontend:release.2025-06-25.v3
    ports:
      - "5173:80"
    environment:
      VITE_FAIRSCAPE_API_URL: "http://localhost:8080/api"
      SEMANTIC_SEARCH_ENABLED: "false"
    depends_on:
      - fairscape-api
      - mongo
      - minio

  redis:
    image: redis:7.2.4
    ports:
      - 6379:6379
  mongo:
    image: mongo:8.0.0-rc20-noble
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongotestaccess
      MONGO_INITDB_ROOT_PASSWORD: mongotestsecret
      MONGO_INITDB_DATABASE: admin
    ports:
      - 27017:27017
    command: ["mongod", "--auth"]
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: meadmin
      ME_CONFIG_BASICAUTH_PASSWORD: meadmin
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongotestaccess
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongotestsecret
      ME_CONFIG_MONGODB_URL: mongodb://mongotestaccess:mongotestsecret@mongo:27017/
    links:
      - mongo:mongo
  minio:
    image: minio/minio:latest
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: miniotestadmin
      MINIO_ROOT_PASSWORD: miniotestsecret
    command: server /data --console-address ":9001"
