# Docker Compose Spec for Local Testing of Fairscape
services:
  fairscape:
    build: .
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    links:
    - mongo:mongo
    - minio:minio
  mongo:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongotestaccess
      MONGO_INITDB_ROOT_PASSWORD: mongotestsecret
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongotestaccess
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongotestsecret
      ME_CONFIG_MONGODB_URL: mongodb://mongotestaccess:mongotestsecret@mongo:27017/
    links:
    - mongo:mongo
  minio:
    image: minio/minio:RELEASE.2023-08-16T20-17-30Z.hotfix.a51234923
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
