services:
  dev:
    entrypoint:
    - sleep
    - infinity
    image: python:3.11.4
    init: true
    links:
      - "mongo:mongo"
      - "minio:minio"
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongotestaccess
      MONGO_INITDB_ROOT_PASSWORD: mongotestsecret
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8080:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongotestaccess
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongotestsecret
      ME_CONFIG_MONGODB_URL: mongodb://mongotestaccess:mongotestsecret@mongo:27017/
  minio:
    image: minio/minio
    restart: always
    ports:
      - 9001:9001
      - 9000:9000
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: miniotestuser
      MINIO_ROOT_PASSWORD: miniotestpass