# Docker Compose Spec for Local Testing of Fairscape
services:
  ldap-frontend:
    image: dnknth/ldap-ui
    environment:
      LDAP_URL: ldap://ldap:1389
      BASE_DN: "dc=fairscape,dc=net"
    ports:
      - 5000:5000

  ldap:
    image: bitnami/openldap:latest
    environment:
      LDAP_ADMIN_USERNAME: "admin"
      LDAP_ADMIN_PASSWORD: "adminpassword"
      LDAP_USERS: "fairscapeUser"
      LDAP_PASSWORDS: "fairscapePass"
      LDAP_ROOT: "dc=fairscape,dc=net"
      LDAP_ADMIN_DN: "cn=admin,dc=fairscape,dc=net"
    ports:
      - 1389:1389
  redis:
    image: redis:7.2.4
    ports:
      - 6379:6379
  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - type: bind
        source: ./deploy/mongo/
        target: /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongotestaccess
      MONGO_INITDB_ROOT_PASSWORD: mongotestsecret
      MONGO_INITDB_DATABASE: admin
    ports:
      - 27017:27017
    command: [ "mongod", "--auth" ]
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: meadmin
      ME_CONFIG_BASICAUTH_PASSWORD: meadmin
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongotestaccess
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongotestsecret
      ME_CONFIG_MONGODB_URL: mongodb://mongotestaccess:mongotestsecret@mongo:27017/
    links:
      - mongo:mongo
  minio:
    image: minio/minio:RELEASE.2023-08-16T20-17-30Z.hotfix.a51234923
    restart: always
    volumes:
      - type: bind
        source: ./deploy/minio_config
        target: /etc/default/minio
      - type: bind
        source: ./deploy/minio/
        target: /mnt/minio/
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: miniotestadmin
      MINIO_ROOT_PASSWORD: miniotestsecret
    command: server /mnt/minio --console-address ":9001"
