# Docker Compose File for Local Testing for Backend API Tasks

version: '3.1'

services:

#  mds:
#    build: .
#    ports:
#    - 8080:8080

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass 
      ME_CONFIG_MONGODB_URL: mongodb://root:rootpass@mongo:27017/

  minio:
    image: minio/minio
    restart: always
    ports:
      - 9001:9001
      - 9000:9000
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: testroot
      MINIO_ROOT_PASSWORD: testroot
