apiVersion: v1
kind: Pod
metadata:
  name: fairscape
  labels:
    app: fairscape
spec:
  containers:
  - name: fairscape
    image: jackofsum/fairscape:0.0.1
    ports:
    - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: fairscape-svc
  labels:
    app: fairscape
spec:
  type: NodePort
  selector:
    app: fairscape
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    NodePort: 30000 
---
apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  containers:
  - name: mongo
    image: mongo
    env:
    - name: MONGO_INITDB_ROOT_USERNAME
      value: root
    - name: MONGO_INITDB_ROOT_PASSWORD
      value: example
    ports:
      - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  labels:
    app: mongo
spec: 
  type: ClusterIP
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: minio
  labels:
    app: minio
spec:
  containers:
  - name: minio
    image: minio/minio
    env:
    - name: MINIO_ROOT_USER
      value: testroot
    - name: MINIO_ROOT_PASSWORD
      value: testroot
    ports:
    - containerPort: 9000
    - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: default
  labels:
    app: minio
spec:
  type: ClusterIP
  selector:
    app: minio
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP